---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.namespace.name }}-netpol
  namespace: {{ .Values.namespace.name }}
spec:
  podSelector: {} # all pods
  ingress: # can receive traffic from all pods in the same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/teamName: {{ .Values.inputs.teamName }}
  egress: # can send traffic to all pods in the same namespace
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/teamName: {{ .Values.inputs.teamName }}
