---
# Source: hello-kubernetes/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: about-releasename-sa
  namespace: default
  labels:
    app.kubernetes.io/name: about-releasename
    app.kubernetes.io/instance: releasename
---
# Source: hello-kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: about-releasename
  namespace: default
  labels:
    app.kubernetes.io/name: about-releasename
    app.kubernetes.io/instance: releasename
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: about-releasename
    app.kubernetes.io/instance: releasename
---
# Source: hello-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-releasename
  namespace: default
  labels:
    app.kubernetes.io/name: about-releasename
    app.kubernetes.io/instance: releasename
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: about-releasename
      app.kubernetes.io/instance: releasename
  template:
    metadata:
      labels:
        app.kubernetes.io/name: about-releasename
        app.kubernetes.io/instance: releasename
    spec:
      serviceAccountName: about-releasename-sa
      containers:
        - name: about-releasename
          image: "paulbouwer/hello-kubernetes:1.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTAINER_IMAGE
            value: "Created with paulbouwer/hello-kubernetes:1.10"
