---
# Source: hello-kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: about-{{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
{{- template "chart.commonLabels" }}
    app.kubernetes.io/name: about-{{ .Values.namespace.name }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: about-{{ .Values.namespace.name }}

---
# Source: hello-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-{{ .Values.namespace.name }}
  namespace: default
{{- template "chart.commonLabels" }}
    app.kubernetes.io/name: about-{{ .Values.namespace.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: about-{{ .Values.namespace.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: about-{{ .Values.namespace.name }}
    spec:
      serviceAccountName: {{ .Values.namespace.name }}-sa
      containers:
        - name: about-{{ .Values.namespace.name }}-container
          image: "paulbouwer/hello-kubernetes:1.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTAINER_IMAGE
            value: "Created with paulbouwer/hello-kubernetes:1.10"
