---
apiVersion: v1
kind: Service
metadata:
  name: about-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: about
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: about

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-dep
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: about
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: about
  template:
    metadata:
      labels:
        app.kubernetes.io/name: about
    spec:
      serviceAccountName: {{ .Values.namespace.name }}-sa
      containers:
        - name: about-container
          image: "paulbouwer/hello-kubernetes:1.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTAINER_IMAGE
            value: "Created with paulbouwer/hello-kubernetes:1.10"
