---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-limit-range
  namespace: {{ .Values.namespace.name }}
{{- template "chart.commonLabels" . }}
spec:
  limits:
    - type: Container
      min:
        cpu: {{ .Values.limits.minCpu | quote }}
        memory: {{ .Values.limits.minMemory }}
      max:
        cpu: {{ .Values.limits.maxCpu | quote }}
        memory: {{ .Values.limits.maxMemory }}
      default:
        cpu: {{ .Values.limits.minCpu | quote }}
        memory: {{ .Values.limits.minMemory }}
      defaultRequest:
        cpu: {{ .Values.limits.minCpu | quote }}
        memory: {{ .Values.limits.minMemory }}
    - type: PersistentVolumeClaim
      max:
        storage: {{ .Values.limits.maxStorage }} 
      min:
        storage: 128Mi
